name: CI/CD to AWS EC2

on:
  push:
    branches:
      - main  # Cambia a la rama que deseas usar para desplegar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '11'  # Usa la versión de Java que necesites
            distribution: 'temurin'  # Especifica la distribución de Java

      - name: Build with Maven
        run: mvn clean install -DskipTests  # Construye el proyecto sin pruebas

      - name: Transfer files via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${EC2_KEY}" > ec2-key.pem
          chmod 400 ec2-key.pem
          scp -i ec2-key.pem target/myapp.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar

      - name: Restart pedidos.service on EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
              sudo systemctl stop pedidos.service
              sudo mv /home/$EC2_USER/app.jar /path/to/your/service/app.jar  # Ajusta esta ruta a la del archivo jar en tu servicio
              sudo systemctl start pedidos.service
              sudo systemctl status pedidos.service
            EOF
