name: CI/CD for Microservicio-Productos

on:
  push:
    branches:
      - main  # Cambia a la rama que deseas usar para desplegar
    paths:
      - 'Microservicio-Productos/**'  # Se ejecuta solo si hay cambios en esta carpeta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle
      run: chmod +x Microservicio-Productos/gradlew  # Da permisos de ejecución a gradlew


    - name: Build with Gradle
      working-directory: Microservicio-Productos  # Cambia al directorio del microservicio
      run: ./gradlew clean build -x test  # Comando Gradle para construir el proyecto sin ejecutar pruebas

    - name: Transfer files via SSH
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${EC2_KEY}" > ec2-key.pem
        chmod 400 ec2-key.pem
        scp -o StrictHostKeyChecking=no -i ec2-key.pem Microservicio-Productos/build/libs/productos.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/productos.jar

    - name: Restart productos.service on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST \
        "sudo systemctl stop productos.service && sudo systemctl start productos.service && sudo systemctl status productos.service"
