name: CI/CD for Microservicio-Pedidos

on:
  push:
    branches:
      - main
    paths:
      - 'Microservicio-Pedidos/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x Microservicio-Pedidos/gradlew

      - name: Create Firebase credentials file
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > Microservicio-Pedidos/src/main/resources/serviceaccount.json

      - name: Verify Firebase credentials file
        run: cat Microservicio-Pedidos/src/main/resources/serviceaccount.json

      - name: Set up EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: Set environment variables on server
        env:
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USER: ${{ secrets.EC2_USER }}
            MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
            TEST_KEY: ${{ secrets.TEST_KEY }}
            PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
            IZIPAY_BASE_URL: ${{ secrets.IZIPAY_BASE_URL }}
        run: |
            ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST \
            "echo 'EC2_HOST=${EC2_HOST}' | sudo tee -a /etc/environment && \
             echo 'MERCHANT_ID=${MERCHANT_ID}' | sudo tee -a /etc/environment && \
             echo 'TEST_KEY=${TEST_KEY}' | sudo tee -a /etc/environment && \
             echo 'PRODUCTION_KEY=${PRODUCTION_KEY}' | sudo tee -a /etc/environment && \
             echo 'SECRET_KEY=${SECRET_KEY}' | sudo tee -a /etc/environment && \
             echo 'PUBLIC_KEY=${PUBLIC_KEY}' | sudo tee -a /etc/environment && \
             echo 'IZIPAY_BASE_URL=${IZIPAY_BASE_URL}' | sudo tee -a /etc/environment"

      - name: Build with Gradle
        working-directory: Microservicio-Pedidos
        run: ./gradlew clean bootJar -x test

      - name: Transfer files via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          scp -o StrictHostKeyChecking=no -i ec2-key.pem Microservicio-Pedidos/build/libs/pedidos.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/pedidos.jar

      - name: Restart pedidos.service on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST \
          "sudo systemctl stop pedidos.service && sudo systemctl start pedidos.service && sudo systemctl status pedidos.service"
